import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { userLoaderStatus } from "@/loaders/user-loader";
import { SidebarProvider, SidebarTrigger } from "@/common/shadcn/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const auth = await userLoaderStatus();
  console.log(auth);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider
        style={{
        "--sidebar-width": "20rem",
         "--sidebar-width-mobile": "20rem"
        } as React.CSSProperties }
        >
        <AppSidebar />
        <main>
          <SidebarTrigger />
        {children}
        </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
